# Generated by Django 4.1.3 on 2022-11-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_certificate_person_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('actor', 'actor'), ('director', 'director'), ('screenwriter', 'screenwriter')], default='actor', verbose_name='role'),
        ),
    ]
